# Generated by Django 5.0 on 2023-12-24 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_rename_user_author_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='author',
            new_name='user',
        ),
    ]
