# Generated by Django 5.0 on 2023-12-24 14:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_rename_author_author_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_time_in',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
