# Generated by Django 5.0 on 2023-12-27 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_comment_comment_time_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='', max_length=240),
        ),
    ]
