# Generated by Django 5.0.1 on 2024-02-14 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_alter_category_subscribers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categories_post',
            field=models.ManyToManyField(related_name='cat_by_post', through='news.PostCategory', to='news.category'),
        ),
    ]
