# Generated by Django 5.0.1 on 2024-02-14 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_alter_post_categories_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categories_post',
            field=models.ManyToManyField(related_name='cat_by_posts', through='news.PostCategory', to='news.category'),
        ),
    ]
