# Generated by Django 5.0.1 on 2024-03-09 06:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_alter_author_options_alter_category_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='rating',
            field=models.IntegerField(default=0, verbose_name='Ratiing'),
        ),
        migrations.AlterField(
            model_name='author',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='category',
            name='subscribers',
            field=models.ManyToManyField(related_name='categories', to=settings.AUTH_USER_MODEL, verbose_name='Subscribers'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_rate',
            field=models.IntegerField(default=0, verbose_name='Comment rate'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_text',
            field=models.TextField(blank=True, verbose_name='Comment text'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_time_in',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Comment time'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.post', verbose_name='Post'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.author', verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='post',
            name='choice_types',
            field=models.CharField(choices=[('NE', 'Новости'), ('AR', 'Статьи')], default='NE', max_length=2, verbose_name='Choice of Types'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(verbose_name='Context'),
        ),
        migrations.AlterField(
            model_name='post',
            name='rate_new',
            field=models.IntegerField(default=0, verbose_name='New rate'),
        ),
        migrations.AlterField(
            model_name='post',
            name='time_in',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Time zone'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='', max_length=240, verbose_name='Title'),
        ),
    ]
